version: 2.1

workflows:
  version: 2
  QA:
    jobs:
      - sbt-paytouch
      - domain:
          requires:
            - sbt-paytouch
      - pt_core:
          requires:
            - domain
      - pt_ordering:
          requires:
            - pt_core

jobs:
  sbt-paytouch:
    executor: jdk
    steps:
      - checkout
      - restore_all_dependencies
      - run:
          command: |
            cd sbt-paytouch
            sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
      - cache_dependencies_across_workflows
      - cache_compilation_within_workflow:
          project: sbt-paytouch

  domain:
    executor: jdk
    steps:
      - checkout
      - restore_all_dependencies
      - restore_all_compilations
      - run:
          command: |
            cd domain
            sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
      - cache_dependencies_across_workflows:
          project: domain
      - cache_compilation_within_workflow:
          project: domain

  pt_core:
    executor: jdk
    steps:
      - checkout
      - restore_all_dependencies
      - restore_all_compilations
      - run:
          command: |
            cd pt_core
            sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
      - cache_dependencies_across_workflows:
          project: pt_core
      - cache_compilation_within_workflow:
          project: pt_core

  pt_ordering:
    executor: jdk
    steps:
      - checkout
      - restore_all_dependencies
      - restore_all_compilations
      - run:
          command: |
            cd pt_ordering
            sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
      - cache_dependencies_across_workflows:
          project: pt_ordering

executors:
  jdk:
    docker:
      - image: circleci/openjdk:8

commands:
  cache_dependencies_across_workflows:
    description: "Caches coursier, ivy2, m2 and sbt artifacts."
    parameters:
      project:
        description: project (circleci doesn't evaluate env variables so we can't use $CIRCLE_JOB here)
        type: string
        default: $CIRCLE_JOB
    steps:
      - run:
          name: echo
          command: |
            echo << parameters.project >>
            echo $CIRCLE_JOB
      - save_cache:
          key: v0-<< parameters.project >>-dependencies-{{ checksum "sbt-paytouch/project/plugins.sbt" }}-{{ checksum "sbt-paytouch/build.sbt" }}-{{ checksum "sbt-paytouch/src/main/scala/io/paytouch/sbtplugin/Paytouch.scala" }}
          paths:
            - ~/.cache/coursier
            - ~/.ivy2/cache
            - ~/.m2
            - ~/.sbt

  restore_all_dependencies:
    description: "Restores sbt output (the target) folder from cache."
    steps:
      - restore_single_project_depenencies:
          project: sbt-paytouch
      - restore_single_project_depenencies:
          project: domain
      - restore_single_project_depenencies:
          project: pt_core
      - restore_single_project_depenencies:
          project: pt_ordering

  restore_single_project_depenencies:
    description: Restores coursier, ivy2, m2 and sbt artifacts from cache.
    parameters:
      project:
        description: project
        type: string
    steps:
      - restore_cache:
          name: Restoring << parameters.project >> dependencies
          key: v0-<< parameters.project >>-dependencies-{{ checksum "sbt-paytouch/project/plugins.sbt" }}-{{ checksum "sbt-paytouch/build.sbt" }}-{{ checksum "sbt-paytouch/src/main/scala/io/paytouch/sbtplugin/Paytouch.scala" }}

  cache_compilation_within_workflow:
    description: Caches sbt output (the target) folder.
    parameters:
      project:
        description: project (circleci doesn't evaluate env variables so we can't use $CIRCLE_JOB here)
        type: string
    steps:
      - run:
          name: Work around incremental compilation issues by preserving timestamps in nanoseconds
          command: |
            cd << parameters.project >>
            find -name target -exec tar -zcf targets.tar.gz -H posix {} +
      - persist_to_workspace:
          root: ~/project
          paths:
            - << parameters.project >>/targets.tar.gz

  restore_all_compilations:
    description: "Restores sbt output (the target) folder from cache."
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - restore_single_project_compilation:
          project: sbt-paytouch
      - restore_single_project_compilation:
          project: domain
      - restore_single_project_compilation:
          project: pt_core
      - restore_single_project_compilation:
          project: pt_ordering

  restore_single_project_compilation:
    description: "Restores sbt output (the target) folder from cache."
    parameters:
      project:
        description: project
        type: string
    steps:
      - run:
          name: Restoring << parameters.project >> compilation (step succeeds even if restoration fails)
          command: |
            tar -xvf /tmp/workspace/<< parameters.project >>/targets.tar.gz --directory ~/project/<< parameters.project >> || true
