version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: Trigger build for modified projects
          shell: /bin/bash
          command: tools/ci/core/build.sh

  sbt-paytouch:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/sbt-paytouch
    steps:
      - checkout
      - run:
          command: |
            sbt compile

  domain:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/domain
    steps:
      - checkout
      - run:
          command: |
            sbt test

  pt_core:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/pt_core
    steps:
      - checkout
      - run:
          command: |
            sbt test

  pt_ordering:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/pt_core
    steps:
      - checkout
      - run:
          command: |
            sbt test
