version: 2.1

workflows:
  version: 2
  QA:
    jobs:
      - sbt-paytouch
      - domain:
          requires:
            - sbt-paytouch
      - pt_core:
          requires:
            - domain
      - pt_ordering:
          requires:
            - pt_core

jobs:
  sbt-paytouch:
    executor: jdk
    steps:
      - checkout
      - restore_dependencies
      - run:
          command: |
            cd sbt-paytouch
            sbt compile
      - cache_dependencies_across_workflows
      - cache_compilation_within_workflow:
          project: sbt-paytouch

  domain:
    executor: jdk
    steps:
      - checkout
      - restore_dependencies
      - restore_compilation
      - run:
          command: |
            cd domain
            sbt compile
      - cache_dependencies_across_workflows
      - cache_compilation_within_workflow:
          project: domain

  pt_core:
    executor: jdk
    steps:
      - checkout
      - restore_dependencies
      - restore_compilation
      - run:
          command: |
            cd pt_core
            sbt compile
      - cache_dependencies_across_workflows
      - cache_compilation_within_workflow:
          project: pt_core

  pt_ordering:
    executor: jdk
    steps:
      - checkout
      - restore_dependencies
      - restore_compilation
      - run:
          command: |
            cd pt_ordering
            sbt compile
      - cache_dependencies_across_workflows

executors:
  jdk:
    docker:
      - image: circleci/openjdk:8

commands:
  cache_dependencies_across_workflows:
    description: "Caches coursier, ivy2, m2 and sbt artifacts."
    steps:
      - save_cache:
          key: dependencies
          paths:
            - ~/.cache/coursier
            - ~/.ivy2/cache
            - ~/.m2
            - ~/.sbt

  restore_dependencies:
    description: Restores coursier, ivy2, m2 and sbt artifacts from cache.
    steps:
      - restore_cache:
          key: dependencies

  cache_compilation_within_workflow:
    description: Caches sbt output (the target) folder.
    parameters:
      project:
        description: project (circleci doesn't evaluate env variables so we can't use $CIRCLE_JOB here)
        type: string
    steps:
      - run:
          name: Work around incremental compilation issues by preserving timestamps in nanoseconds
          command: |
            cd << parameters.project >>
            find -name target -exec tar -zcf targets.tar.gz -H posix {} +

      - persist_to_workspace:
          root: ~/project
          paths:
            - << parameters.project >>/targets.tar.gz

  restore_compilation:
    description: "Restores sbt output (the target) folder from cache."
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: tar -xvf /tmp/workspace/sbt-paytouch/targets.tar.gz --directory ~/project/sbt-paytouch || true
      - run: tar -xvf /tmp/workspace/domain/targets.tar.gz --directory ~/project/domain || true
      - run: tar -xvf /tmp/workspace/pt_core/targets.tar.gz --directory ~/project/pt_core || true
      - run: tar -xvf /tmp/workspace/pt_ordering/targets.tar.gz --directory ~/project/pt_ordering || true
