version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: Trigger build for modified projects
          shell: /bin/bash
          command: tools/ci/core/build.sh

  server:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project/server
    steps:
      - checkout:
          path: ~/project
      - run:
          command: |
            echo Build Server

  client:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project/client
    steps:
      - checkout:
          path: ~/project
      - run:
          command: |
            echo Build Client

  common:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project/common
    steps:
      # - checkout:
      #     path: ~/project
      - run:
          command: |
            echo Build Common
