version: 2.1

workflows:
  version: 2
  QA:
    jobs:
      - sbt-paytouch
      - domain:
          requires:
            - sbt-paytouch
      - pt_core:
          requires:
            - domain
      - pt_ordering:
          requires:
            - pt_core

jobs:
  sbt-paytouch:
    executor: jdk
    steps:
      - checkout
      - restore_dependencies
      - run:
          command: |
            cd sbt-paytouch
            sbt compile
      - cache_dependencies_across_workflows
      - cache_compilation_within_workflow:
          project: sbt-paytouch

  domain:
    executor: jdk
    steps:
      - checkout
      - restore_dependencies
      - restore_all_compilations
      - run:
          command: |
            cd domain
            sbt compile
      - cache_dependencies_across_workflows
      - cache_compilation_within_workflow:
          project: domain

  pt_core:
    executor: jdk
    steps:
      - checkout
      - restore_dependencies
      - restore_all_compilations
      - run:
          command: |
            cd pt_core
            sbt compile
      - cache_dependencies_across_workflows
      - cache_compilation_within_workflow:
          project: pt_core

  pt_ordering:
    executor: jdk
    steps:
      - checkout
      - restore_dependencies
      - restore_all_compilations
      - run:
          command: |
            cd pt_ordering
            sbt compile
      - cache_dependencies_across_workflows

executors:
  jdk:
    docker:
      - image: circleci/openjdk:8

commands:
  cache_dependencies_across_workflows:
    description: "Caches coursier, ivy2, m2 and sbt artifacts."
    steps:
      - save_cache:
          key: dependencies
          paths:
            - "~/.cache/coursier"
            - "~/.ivy2/cache"
            - "~/.m2"
            - "~/.sbt"

  restore_dependencies:
    description: Restores coursier, ivy2, m2 and sbt artifacts from cache.
    steps:
      - restore_cache:
          key: dependencies

  cache_compilation_within_workflow:
    description: Caches sbt output (the target) folder.
    parameters:
      project:
        description: project (circleci doesn't evaluate env variables so we can't use $CIRCLE_JOB here)
        type: string
    steps:
      - run:
          name: Work around incremental compilation issues by preserving timestamps in nanoseconds
          command: |
            cd << parameters.project >>
            find -name target -exec tar -zcf targets.tar.gz -H posix {} +

      - persist_to_workspace:
          root: ~/project
          paths:
            - << parameters.project >>/targets.tar.gz

  restore_all_compilations:
    description: "Restores sbt output (the target) folder from cache."
    steps:
      - restore_one_compilation:
          project: sbt-paytouch
      - restore_one_compilation:
          project: domain
      - restore_one_compilation:
          project: pt_core
      - restore_one_compilation:
          project: pt_ordering

  restore_one_compilation:
    description: "Restores sbt output (the target) folder from cache."
    parameters:
      project:
        description: project (circleci doesn't evaluate env variables so we can't use $CIRCLE_JOB here)
        type: string
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Restore << parameters.project >> (step succeeds even if restoration fails)
          command: |
            tar -xvf /tmp/workspace/<< parameters.project >>/targets.tar.gz --directory ~/project/<< parameters.project >> || true
