version: 2.1

workflows:
  version: 2
  QA:
    jobs:
      # determine which projects/jobs need to be rerun and which can be skipped
      - tag-changed-projects

      # compile
      - sbt-paytouch:
          name: sbt-paytouch-compile
          task: compile
          requires:
            - tag-changed-projects
          # resource_class: medium+
      - authentikat-jwt:
          name: authentikat-jwt-compile
          task: compile
          requires:
            - sbt-paytouch-compile
          # resource_class: medium+
      - domain:
          name: domain-compile
          task: compile
          requires:
            - sbt-paytouch-compile
          # resource_class: medium+
      - pt_core:
          name: pt_core-compile
          task: compile
          requires:
            - authentikat-jwt-compile
            - domain-compile
          # resource_class: medium+
      - pt_ordering:
          name: pt_ordering-compile
          task: compile
          requires:
            - authentikat-jwt-compile
            - domain-compile
          # resource_class: medium+

      # test:compile
      - sbt-paytouch:
          name: sbt-paytouch-test:compile
          task: test:compile
          requires:
            - sbt-paytouch-compile
          # resource_class: medium+
      - authentikat-jwt:
          name: authentikat-jwt-test:compile
          task: test:compile
          requires:
            - sbt-paytouch-test:compile
            - authentikat-jwt-compile
          # resource_class: medium+
      - domain:
          name: domain-test:compile
          task: test:compile
          requires:
            - sbt-paytouch-test:compile
            - domain-compile
          # resource_class: medium+
      - pt_core:
          name: pt_core-test:compile
          task: test:compile
          requires:
            - pt_core-compile
            - authentikat-jwt-test:compile
            - domain-test:compile
          # resource_class: medium+
      - pt_ordering:
          name: pt_ordering-test:compile
          task: test:compile
          requires:
            - pt_ordering-compile
            - authentikat-jwt-test:compile
            - domain-test:compile
          # resource_class: medium+

      # test
      - sbt-paytouch:
          name: sbt-paytouch-test
          task: test
          requires:
            - sbt-paytouch-test:compile
          # resource_class: medium
      - authentikat-jwt:
          name: authentikat-jwt-test
          task: test
          requires:
            - authentikat-jwt-test:compile
          # resource_class: medium
      - domain:
          name: domain-test
          task: test
          requires:
            - domain-test:compile
          # resource_class: medium
      - pt_core:
          name: pt_core-test
          executor: jdk-postgres-redis
          task: test
          requires:
            - pt_core-test:compile
          # resource_class: medium
      - pt_ordering:
          name: pt_ordering-test
          executor: jdk-postgres-redis
          task: test
          requires:
            - pt_ordering-test:compile
          # resource_class: medium

      # package
      - pt_core:
          name: pt_core-package
          executor: jdk
          task: package
          requires:
            - pt_core-test
          # resource_class: medium
      - pt_ordering:
          name: pt_ordering-package
          executor: jdk
          task: package
          requires:
            - pt_ordering-test
          # resource_class: medium

jobs:
  tag-changed-projects:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Determining which projects were changed since the last successful run
          shell: /bin/bash
          command: tools/ci/core/build.sh
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - projects-with-changes

  sbt-paytouch:
    parameters:
      task:
        description: compile, test:compile or test
        type: enum
        enum: ["compile", "test:compile", "test"]
      resource_class:
        type: string
        default: small
    executor: jdk
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run_or_skip:
          project: sbt-paytouch
      - restore_single_project_dependencies:
          project: sbt-paytouch
      - run:
          name: Running the actual job
          environment:
            CIRCLECI: "true"
          command: |
            cd sbt-paytouch
            if [ << parameters.task >> = "compile" ]; then
              sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
            else
              sbt << parameters.task >>
            fi
      - cache_dependencies_across_workflows:
          project: sbt-paytouch
      - cache_all_compilations_within_workflow

  authentikat-jwt:
    parameters:
      task:
        description: compile, test:compile or test
        type: enum
        enum: ["compile", "test:compile", "test"]
      resource_class:
        type: string
        default: small
    executor: jdk
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run_or_skip:
          project: authentikat-jwt
      - restore_single_project_dependencies:
          project: sbt-paytouch
      - restore_single_project_dependencies:
          project: authentikat-jwt
      - restore_all_compilations
      - run:
          name: Running the actual job
          environment:
            CIRCLECI: "true"
          command: |
            cd authentikat-jwt
            if [ << parameters.task >> = "compile" ]; then
              sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
            else
              sbt << parameters.task >>
            fi
      - cache_dependencies_across_workflows:
          project: authentikat-jwt
      - cache_all_compilations_within_workflow

  domain:
    parameters:
      task:
        description: compile, test:compile or test
        type: enum
        enum: ["compile", "test:compile", "test"]
      resource_class:
        type: string
        default: small
    executor: jdk
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run_or_skip:
          project: domain
      - restore_single_project_dependencies:
          project: sbt-paytouch
      - restore_single_project_dependencies:
          project: domain
      - restore_all_compilations
      - run:
          name: Running the actual job
          environment:
            CIRCLECI: "true"
          command: |
            cd domain
            if [ << parameters.task >> = "compile" ]; then
              sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
            else
              sbt << parameters.task >>
            fi
      - cache_dependencies_across_workflows:
          project: domain
      - cache_all_compilations_within_workflow

  pt_core:
    parameters:
      task:
        description: compile, test:compile or test
        type: enum
        enum: ["compile", "test:compile", "test", "package"]
      executor:
        type: enum
        enum: ["jdk", "jdk-postgres-redis"]
        default: "jdk"
      resource_class:
        type: string
        default: small
    executor: << parameters.executor >>
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run_or_skip:
          project: pt_core
      - restore_single_project_dependencies:
          project: sbt-paytouch
      - restore_single_project_dependencies:
          project: authentikat-jwt
      - restore_single_project_dependencies:
          project: domain
      - restore_single_project_dependencies:
          project: pt_core
      - restore_all_compilations
      - run:
          name: Running the actual job
          environment:
            CIRCLECI: "true"
          command: |
            cd pt_core
            if [ << parameters.task >> = "compile" ]; then
              bin/build_swagger && \
              sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
            elif [ << parameters.task >> = "package" ]; then
              echo 'sbt dockerBuildAndPush'
            else
              sbt << parameters.task >>
            fi
      - cache_dependencies_across_workflows:
          project: pt_core
      - cache_all_compilations_within_workflow

  pt_ordering:
    parameters:
      task:
        description: compile, test:compile or test
        type: enum
        enum: ["compile", "test:compile", "test", "package"]
      executor:
        type: enum
        enum: ["jdk", "jdk-postgres-redis"]
        default: "jdk"
      resource_class:
        type: string
        default: small
    executor: << parameters.executor >>
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run_or_skip:
          project: pt_ordering
      - restore_single_project_dependencies:
          project: sbt-paytouch
      - restore_single_project_dependencies:
          project: authentikat-jwt
      - restore_single_project_dependencies:
          project: domain
      - restore_single_project_dependencies:
          project: pt_ordering
      - restore_all_compilations
      - run:
          name: Running the actual job
          environment:
            CIRCLECI: "true"
          command: |
            cd pt_ordering
            if [ << parameters.task >> = "compile" ]; then
              bin/build_swagger && \
              sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
            elif [ << parameters.task >> = "package" ]; then
              echo 'sbt dockerBuildAndPush'
            else
              sbt << parameters.task >>
            fi
      - cache_dependencies_across_workflows:
          project: pt_ordering
      - cache_all_compilations_within_workflow

# https://circleci.com/docs/2.0/docker-image-tags.json
executors:
  jdk:
    docker:
      - image: circleci/openjdk:8
  jdk-postgres-redis:
    docker:
      - image: circleci/openjdk:8
      - image: circleci/postgres:9.6.15
      - image: circleci/redis

commands:
  run_or_skip:
    parameters:
      project:
        type: string
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Determining weather project was changed since the last successful run
          command: |
            echo Projects with changes:
            cat /tmp/workspace/projects-with-changes
            echo
            if [ -z $(grep << parameters.project >> /tmp/workspace/projects-with-changes) ]; then
              circleci-agent step halt
            fi

  cache_dependencies_across_workflows:
    description: "Caches coursier, ivy2, m2 and sbt artifacts."
    parameters:
      project:
        type: string
    steps:
      - save_cache:
          key: v0-<< parameters.project >>-dependencies-{{ checksum "sbt-paytouch/project/plugins.sbt" }}-{{ checksum "sbt-paytouch/build.sbt" }}-{{ checksum "sbt-paytouch/src/main/scala/io/paytouch/sbtplugin/Paytouch.scala" }}
          paths:
            - ~/.cache/coursier
            - ~/.ivy2/cache
            - ~/.m2
            - ~/.sbt

  restore_single_project_dependencies:
    description: Restores coursier, ivy2, m2 and sbt artifacts from cache.
    parameters:
      project:
        description: project
        type: string
    steps:
      - restore_cache:
          name: Restoring << parameters.project >> dependencies
          key: v0-<< parameters.project >>-dependencies-{{ checksum "sbt-paytouch/project/plugins.sbt" }}-{{ checksum "sbt-paytouch/build.sbt" }}-{{ checksum "sbt-paytouch/src/main/scala/io/paytouch/sbtplugin/Paytouch.scala" }}

  cache_all_compilations_within_workflow:
    steps:
      - cache_single_project_compilation_within_workflow:
          project: sbt-paytouch
      - cache_single_project_compilation_within_workflow:
          project: authentikat-jwt
      - cache_single_project_compilation_within_workflow:
          project: domain
      - cache_single_project_compilation_within_workflow:
          project: pt_core
      - cache_single_project_compilation_within_workflow:
          project: pt_ordering

  cache_single_project_compilation_within_workflow:
    description: Caches sbt output (the target) folder.
    parameters:
      project:
        type: string
    steps:
      - run:
          name: Work around incremental compilation issues by preserving timestamps in nanoseconds
          command: |
            cd << parameters.project >>
            find -name target -exec tar -zcf targets.tar.gz -H posix {} + || touch targets.tar.gz
      - persist_to_workspace:
          root: ~/project
          paths:
            - << parameters.project >>/targets.tar.gz

  # restore_all_compilations executes instantly so we can always restore all compilations
  # even the ones that we don't need or the ones that don't exist yet.
  restore_all_compilations:
    description: "Restores sbt output (the target) folder from cache."
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - restore_single_project_compilation:
          project: sbt-paytouch
      - restore_single_project_compilation:
          project: authentikat-jwt
      - restore_single_project_compilation:
          project: domain
      - restore_single_project_compilation:
          project: pt_core
      - restore_single_project_compilation:
          project: pt_ordering

  restore_single_project_compilation:
    description: "Restores sbt output (the target) folder from cache."
    parameters:
      project:
        description: project
        type: string
    steps:
      - run:
          name: Restoring << parameters.project >> compilation (succeeds even if restoration fails)
          command: |
            tar -xf /tmp/workspace/<< parameters.project >>/targets.tar.gz --directory ~/project/<< parameters.project >> || true
