version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: Trigger build for modified projects
          shell: /bin/bash
          command: tools/ci/core/build.sh

  sbt-paytouch:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - restore_cache:
          key: sbt-cache
      - run:
          command: |
            cd sbt-paytouch
            sbt compile
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.cache/coursier"
            - "~/.ivy2/cache"
            - "~/.m2"
            - "~/.sbt"
      - persist_to_workspace:
          root: ~/project
          paths:
            - sbt-paytouch/target/*

  domain:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - restore_cache:
          key: sbt-cache
      - run:
          command: |
            cd domain
            sbt test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.cache/coursier"
            - "~/.ivy2/cache"
            - "~/.m2"
            - "~/.sbt"
      - persist_to_workspace:
          root: ~/project
          paths:
            - domain/target/*

  pt_core:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - restore_cache:
          key: sbt-cache
      - run:
          command: |
            cd pt_core
            sbt test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.cache/coursier"
            - "~/.ivy2/cache"
            - "~/.m2"
            - "~/.sbt"
      - persist_to_workspace:
          root: ~/project
          paths:
            - pt_core/target/*

  pt_ordering:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - restore_cache:
          key: sbt-cache
      - run:
          command: |
            cd pt_ordering
            sbt test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.cache/coursier"
            - "~/.ivy2/cache"
            - "~/.m2"
            - "~/.sbt"
      - persist_to_workspace:
          root: ~/project
          paths:
            - pt_ordering/target/*
