version: 2.1

workflows:
  version: 2
  QA:
    jobs:
      # determine which projects/jobs need to be rerun and which can be skipped
      - tag-changed-projects

      # compile
      - sbt-paytouch:
          name: sbt-paytouch-compile
          config: main
          task: compile
          always_run_never_skip: true
          requires:
            - tag-changed-projects
          # resource_class: medium+
      - authentikat-jwt:
          name: authentikat-jwt-compile
          config: main
          task: compile
          always_run_never_skip: true
          requires:
            - sbt-paytouch-compile
          # resource_class: medium+
      - domain:
          name: domain-compile
          config: main
          task: compile
          always_run_never_skip: true
          requires:
            - sbt-paytouch-compile
          # resource_class: medium+
      - pt_core:
          name: pt_core-compile
          config: main
          task: compile
          requires:
            - authentikat-jwt-compile
            - domain-compile
          # resource_class: medium+
      - pt_ordering:
          name: pt_ordering-compile
          config: main
          task: compile
          requires:
            - authentikat-jwt-compile
            - domain-compile
          # resource_class: medium+

      # test:compile
      - sbt-paytouch:
          name: sbt-paytouch-test:compile
          config: test
          task: test:compile
          always_run_never_skip: true
          requires:
            - sbt-paytouch-compile
          # resource_class: medium+
      - authentikat-jwt:
          name: authentikat-jwt-test:compile
          config: test
          task: test:compile
          always_run_never_skip: true
          requires:
            - sbt-paytouch-test:compile
            - authentikat-jwt-compile
          # resource_class: medium+
      - domain:
          name: domain-test:compile
          config: test
          task: test:compile
          always_run_never_skip: true
          requires:
            - sbt-paytouch-test:compile
            - domain-compile
          # resource_class: medium+
      - pt_core:
          name: pt_core-test:compile
          config: test
          task: test:compile
          requires:
            - pt_core-compile
            - authentikat-jwt-test:compile
            - domain-test:compile
          # resource_class: medium+
      - pt_ordering:
          name: pt_ordering-test:compile
          config: test
          task: test:compile
          requires:
            - pt_ordering-compile
            - authentikat-jwt-test:compile
            - domain-test:compile
          # resource_class: medium+

      # test
      - sbt-paytouch:
          name: sbt-paytouch-test
          config: test
          task: test
          requires:
            - sbt-paytouch-test:compile
          # resource_class: medium
      - authentikat-jwt:
          name: authentikat-jwt-test
          config: test
          task: test
          requires:
            - authentikat-jwt-test:compile
          # resource_class: medium
      - domain:
          name: domain-test
          config: test
          task: test
          requires:
            - domain-test:compile
          # resource_class: medium
      - pt_core:
          name: pt_core-test
          executor: jdk-postgres-redis
          config: test
          task: test
          requires:
            - pt_core-test:compile
          # resource_class: medium
      - pt_ordering:
          name: pt_ordering-test
          executor: jdk-postgres-redis
          config: test
          task: test
          requires:
            - pt_ordering-test:compile
          # resource_class: medium

      # package
      - pt_core:
          name: pt_core-package
          executor: jdk
          config: package
          task: package
          requires:
            - pt_core-test
          # resource_class: medium
      - pt_ordering:
          name: pt_ordering-package
          executor: jdk
          config: package
          task: package
          requires:
            - pt_ordering-test
          # resource_class: medium

jobs:
  tag-changed-projects:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Determining which projects were changed since the last successful run
          shell: /bin/bash
          command: tools/ci/core/build.sh
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - projects-with-changes
  sbt-paytouch:
    parameters:
      config:
        description: main or test
        type: enum
        enum: ["main", "test"]
      task:
        description: compile, test:compile or test
        type: enum
        enum: ["compile", "test:compile", "test"]
      always_run_never_skip:
        type: boolean
        default: false
      resource_class:
        type: string
        default: small
    executor: jdk
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run_or_skip:
          project: sbt-paytouch
          always_run_never_skip: << parameters.always_run_never_skip >>
      - restore_single_project_depenencies:
          project: sbt-paytouch
      - run:
          name: Running the actual job
          command: |
            cd sbt-paytouch
            if [ << parameters.task >> = "compile" ]; then
              sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
            else
              sbt << parameters.task >>
            fi
      - cache_dependencies_across_workflows:
          project: sbt-paytouch
      - cache_compilation_within_workflow:
          project: sbt-paytouch
          config: << parameters.config >>

  authentikat-jwt:
    parameters:
      config:
        description: main or test
        type: enum
        enum: ["main", "test"]
      task:
        description: compile, test:compile or test
        type: enum
        enum: ["compile", "test:compile", "test"]
      always_run_never_skip:
        type: boolean
        default: false
      resource_class:
        type: string
        default: small
    executor: jdk
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run_or_skip:
          project: authentikat-jwt
          always_run_never_skip: << parameters.always_run_never_skip >>
      - restore_single_project_depenencies:
          project: sbt-paytouch
      - restore_single_project_depenencies:
          project: authentikat-jwt
      - restore_all_compilations
      - run:
          name: Running the actual job
          command: |
            cd authentikat-jwt
            if [ << parameters.task >> = "compile" ]; then
              sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
            else
              sbt << parameters.task >>
            fi
      - cache_dependencies_across_workflows:
          project: authentikat-jwt
      - cache_compilation_within_workflow:
          project: authentikat-jwt
          config: << parameters.config >>

  domain:
    parameters:
      config:
        description: main or test
        type: enum
        enum: ["main", "test"]
      task:
        description: compile, test:compile or test
        type: enum
        enum: ["compile", "test:compile", "test"]
      always_run_never_skip:
        type: boolean
        default: false
      resource_class:
        type: string
        default: small
    executor: jdk
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run_or_skip:
          project: domain
          always_run_never_skip: << parameters.always_run_never_skip >>
      - restore_single_project_depenencies:
          project: sbt-paytouch
      - restore_single_project_depenencies:
          project: domain
      - restore_all_compilations
      - run:
          name: Running the actual job
          command: |
            cd domain
            if [ << parameters.task >> = "compile" ]; then
              sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
            else
              sbt << parameters.task >>
            fi
      - cache_dependencies_across_workflows:
          project: domain
      - cache_compilation_within_workflow:
          project: domain
          config: << parameters.config >>

  pt_core:
    parameters:
      config:
        description: main or test
        type: enum
        enum: ["main", "test", "package"]
      task:
        description: compile, test:compile or test
        type: enum
        enum: ["compile", "test:compile", "test", "package"]
      always_run_never_skip:
        type: boolean
        default: false
      executor:
        type: enum
        enum: ["jdk", "jdk-postgres-redis"]
        default: "jdk"
      resource_class:
        type: string
        default: small
    executor: << parameters.executor >>
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run_or_skip:
          project: pt_core
          always_run_never_skip: << parameters.always_run_never_skip >>
      - when:
          condition:
            equal: [<< parameters.task >>, "package"]
          steps:
            - setup_remote_docker:
                docker_layer_caching: true
      - restore_single_project_depenencies:
          project: sbt-paytouch
      - restore_single_project_depenencies:
          project: authentikat-jwt
      - restore_single_project_depenencies:
          project: domain
      - restore_single_project_depenencies:
          project: pt_core
      - restore_all_compilations
      - run:
          name: Running the actual job
          environment:
            LIQUIBASE_VERSION: 3.10.2
            GIT_SSH_COMMAND: /usr/bin/ssh -o StrictHostKeyChecking=No
          command: |
            cd pt_core
            if [ << parameters.task >> = "compile" ]; then
              bin/build_swagger && \
              sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
            elif [ << parameters.task >> = "package" ]; then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip -qq awscliv2.zip
              sudo ./aws/install
              aws --version
              aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_REPOSITORY_URL}
              curl -L --silent --retry 3 'https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.datadoghq&a=dd-java-agent&v=LATEST' -o dd-java-agent.jar

              curl -L --silent --retry 3 https://github.com/liquibase/liquibase/releases/download/v$LIQUIBASE_VERSION/liquibase-$LIQUIBASE_VERSION.jar -o liquibase.jar

              sbt dockerBuildAndPush

              git tag vlad-$CIRCLE_BUILD_NUM $CIRCLE_SHA1
              git push origin vlad-$CIRCLE_BUILD_NUM

              mkdir -p ~/workspace
              echo "export BUILD_STEP_BUILD_NUM=vlad-$CIRCLE_BUILD_NUM" >> ~/workspace/build-step-build-num
            else
              sbt << parameters.task >>
            fi
      - cache_dependencies_across_workflows:
          project: pt_core
      - cache_compilation_within_workflow:
          project: pt_core
          config: << parameters.config >>
      - when:
          condition:
            equal: [<< parameters.task >>, "package"]
          steps:
            - persist_to_workspace:
                root: ~/workspace
                paths:
                  - build-step-build-num

  pt_ordering:
    parameters:
      config:
        description: main or test
        type: enum
        enum: ["main", "test", "package"]
      task:
        description: compile, test:compile or test
        type: enum
        enum: ["compile", "test:compile", "test", "package"]
      always_run_never_skip:
        type: boolean
        default: false
      executor:
        type: enum
        enum: ["jdk", "jdk-postgres-redis"]
        default: "jdk"
      resource_class:
        type: string
        default: small
    executor: << parameters.executor >>
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run_or_skip:
          project: pt_ordering
          always_run_never_skip: << parameters.always_run_never_skip >>
      - restore_single_project_depenencies:
          project: sbt-paytouch
      - restore_single_project_depenencies:
          project: authentikat-jwt
      - restore_single_project_depenencies:
          project: domain
      - restore_single_project_depenencies:
          project: pt_ordering
      - restore_all_compilations
      - run:
          name: Running the actual job
          command: |
            cd pt_ordering
            if [ << parameters.task >> = "compile" ]; then
              bin/build_swagger && \
              sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
            elif [ << parameters.task >> = "package" ]; then
              echo 'sbt dockerBuildAndPush'
            else
              sbt << parameters.task >>
            fi
      - cache_dependencies_across_workflows:
          project: pt_ordering
      - cache_compilation_within_workflow:
          project: pt_ordering
          config: << parameters.config >>

# https://circleci.com/docs/2.0/docker-image-tags.json
executors:
  jdk:
    docker:
      - image: circleci/openjdk:8
  jdk-postgres-redis:
    docker:
      - image: circleci/openjdk:8
      - image: circleci/postgres:9.6.15
      - image: circleci/redis

commands:
  run_or_skip:
    parameters:
      project:
        type: string
      always_run_never_skip:
        type: boolean
        default: false
    steps:
      - unless:
          condition: << parameters.always_run_never_skip >>
          steps:
            - attach_workspace:
                at: /tmp/workspace
            - run:
                name: Determining weather project was changed since the last successful run
                command: |
                  echo Projects with changes:
                  cat /tmp/workspace/projects-with-changes
                  echo
                  if [ -z $(grep << parameters.project >> /tmp/workspace/projects-with-changes) ]; then
                    circleci-agent step halt
                  fi

  cache_dependencies_across_workflows:
    description: "Caches coursier, ivy2, m2 and sbt artifacts."
    parameters:
      project:
        type: string
    steps:
      - save_cache:
          key: v0-<< parameters.project >>-dependencies-{{ checksum "sbt-paytouch/project/plugins.sbt" }}-{{ checksum "sbt-paytouch/build.sbt" }}-{{ checksum "sbt-paytouch/src/main/scala/io/paytouch/sbtplugin/Paytouch.scala" }}
          paths:
            - ~/.cache/coursier
            - ~/.ivy2/cache
            - ~/.m2
            - ~/.sbt

  restore_single_project_depenencies:
    description: Restores coursier, ivy2, m2 and sbt artifacts from cache.
    parameters:
      project:
        description: project
        type: string
    steps:
      - restore_cache:
          name: Restoring << parameters.project >> dependencies
          key: v0-<< parameters.project >>-dependencies-{{ checksum "sbt-paytouch/project/plugins.sbt" }}-{{ checksum "sbt-paytouch/build.sbt" }}-{{ checksum "sbt-paytouch/src/main/scala/io/paytouch/sbtplugin/Paytouch.scala" }}

  cache_compilation_within_workflow:
    description: Caches sbt output (the target) folder.
    parameters:
      project:
        type: string
      config:
        description: "Suffix for the cache since workspaces are prepend only we can't reuse the names."
        type: enum
        enum: ["main", "test", "package"]
    steps:
      - run:
          name: Work around incremental compilation issues by preserving timestamps in nanoseconds
          command: |
            cd << parameters.project >>
            find -name target -exec tar -zcf targets-<< parameters.config >>.tar.gz -H posix {} +
      - persist_to_workspace:
          root: ~/project
          paths:
            - << parameters.project >>/targets-<< parameters.config >>.tar.gz

  # restore_all_compilations executes instantly so we can always restore all compilations
  # even the ones that we don't need or the ones that don't exist yet.
  restore_all_compilations:
    description: "Restores sbt output (the target) folder from cache."
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - restore_single_project_compilation:
          project: sbt-paytouch
      - restore_single_project_compilation:
          project: authentikat-jwt
      - restore_single_project_compilation:
          project: domain
      - restore_single_project_compilation:
          project: pt_core
      - restore_single_project_compilation:
          project: pt_ordering

  restore_single_project_compilation:
    description: "Restores sbt output (the target) folder from cache."
    parameters:
      project:
        description: project
        type: string
    steps:
      - restore_single_project_compilation_for_config:
          project: << parameters.project >>
          config: main
      - restore_single_project_compilation_for_config:
          project: << parameters.project >>
          config: test
      - restore_single_project_compilation_for_config:
          project: << parameters.project >>
          config: package

  restore_single_project_compilation_for_config:
    description: "Restores sbt output (the target) folder from cache."
    parameters:
      project:
        description: project
        type: string
      config:
        description: "Suffix for the cache since workspaces are prepend only we can't reuse the names."
        type: enum
        enum: ["main", "test", "package"]
    steps:
      - run:
          name: Restoring << parameters.project >> compilation (succeeds even if restoration fails)
          command: |
            tar -xf /tmp/workspace/<< parameters.project >>/targets-<< parameters.config >>.tar.gz --directory ~/project/<< parameters.project >> || true
