version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: Trigger build for modified projects
          shell: /bin/bash
          command: tools/ci/core/build.sh

  sbt-paytouch:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project/sbt-paytouch
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: sbt-cache
      - run:
          command: |
            sbt compile
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.cache/coursier"
            - "~/.ivy2/cache"
            - "~/.m2"
            - "~/.sbt"

  domain:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project/domain
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: sbt-cache
      - run:
          command: |
            sbt test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.cache/coursier"
            - "~/.ivy2/cache"
            - "~/.m2"
            - "~/.sbt"

  pt_core:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project/pt_core
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: sbt-cache
      - run:
          command: |
            sbt test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.cache/coursier"
            - "~/.ivy2/cache"
            - "~/.m2"
            - "~/.sbt"

  pt_ordering:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project/pt_ordering
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: sbt-cache
      - run:
          command: |
            sbt test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.cache/coursier"
            - "~/.ivy2/cache"
            - "~/.m2"
            - "~/.sbt"
