version: 2.1

workflows:
  version: 2
  QA:
    jobs:
      - sbt-paytouch
      - domain:
          requires:
            - sbt-paytouch
      - pt_core:
          requires:
            - domain
      - pt_ordering:
          requires:
            - pt_core

jobs:
  sbt-paytouch:
    parameters:
      config:
        description: main or test
        type: enum
        enum: ["main", "test"]
        default: "main"
    executor: jdk
    steps:
      - checkout
      - restore_single_project_depenencies:
          project: sbt-paytouch
      - run:
          name: Running the actual job
          command: |
            cd sbt-paytouch
            if [ << parameters.config >> = "main" ]; then
              sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
            else
              sbt test
            fi
      - cache_dependencies_across_workflows:
          project: sbt-paytouch
      - cache_compilation_within_workflow:
          project: sbt-paytouch
          config: << parameters.config >>

  domain:
    parameters:
      config:
        description: main or test
        type: enum
        enum: ["main", "test"]
        default: "main"
    executor: jdk
    steps:
      - checkout
      - restore_single_project_depenencies:
          project: sbt-paytouch
      - restore_single_project_depenencies:
          project: domain
      - restore_all_compilations
      - run:
          name: Running the actual job
          command: |
            cd domain
            if [ << parameters.config >> = "main" ]; then
              sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
            else
              sbt test
            fi
      - cache_dependencies_across_workflows:
          project: domain
      - cache_compilation_within_workflow:
          project: domain
          config: << parameters.config >>

  pt_core:
    parameters:
      config:
        description: main or test
        type: enum
        enum: ["main", "test"]
        default: "main"
    executor: jdk
    steps:
      - checkout
      - restore_single_project_depenencies:
          project: sbt-paytouch
      - restore_single_project_depenencies:
          project: domain
      - restore_single_project_depenencies:
          project: pt_core
      - restore_all_compilations
      - run:
          name: Running the actual job
          command: |
            cd pt_core
            if [ << parameters.config >> = "main" ]; then
              sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
            else
              sbt test
            fi
      - cache_dependencies_across_workflows:
          project: pt_core
      - cache_compilation_within_workflow:
          project: pt_core
          config: << parameters.config >>

  pt_ordering:
    parameters:
      config:
        description: main or test
        type: enum
        enum: ["main", "test"]
        default: "main"
    executor: jdk
    steps:
      - checkout
      - restore_single_project_depenencies:
          project: sbt-paytouch
      - restore_single_project_depenencies:
          project: domain
      - restore_single_project_depenencies:
          project: pt_core
      - restore_single_project_depenencies:
          project: pt_ordering
      - restore_all_compilations
      - run:
          name: Running the actual job
          command: |
            cd pt_ordering
            if [ << parameters.config >> = "main" ]; then
              sbt test:update scalafmtSbtCheck scalafmtCheckAll compile
            else
              sbt test
            fi
      - cache_dependencies_across_workflows:
          project: pt_ordering

executors:
  jdk:
    docker:
      - image: circleci/openjdk:8

commands:
  cache_dependencies_across_workflows:
    description: "Caches coursier, ivy2, m2 and sbt artifacts."
    parameters:
      project:
        description: circleci doesn't evaluate env variables outside of run steps so we can't use $CIRCLE_JOB here
        type: string
    steps:
      - save_cache:
          key: v0-<< parameters.project >>-dependencies-{{ checksum "sbt-paytouch/project/plugins.sbt" }}-{{ checksum "sbt-paytouch/build.sbt" }}-{{ checksum "sbt-paytouch/src/main/scala/io/paytouch/sbtplugin/Paytouch.scala" }}
          paths:
            - ~/.cache/coursier
            - ~/.ivy2/cache
            - ~/.m2
            - ~/.sbt

  restore_single_project_depenencies:
    description: Restores coursier, ivy2, m2 and sbt artifacts from cache.
    parameters:
      project:
        description: project
        type: string
    steps:
      - restore_cache:
          name: Restoring << parameters.project >> dependencies
          key: v0-<< parameters.project >>-dependencies-{{ checksum "sbt-paytouch/project/plugins.sbt" }}-{{ checksum "sbt-paytouch/build.sbt" }}-{{ checksum "sbt-paytouch/src/main/scala/io/paytouch/sbtplugin/Paytouch.scala" }}

  cache_compilation_within_workflow:
    description: Caches sbt output (the target) folder.
    parameters:
      project:
        description: circleci doesn't evaluate env variables outside of run steps so we can't use $CIRCLE_JOB here
        type: string
      config:
        description: will be used as suffix for the cache since workspaces are prepend only we can't reuse the names
        type: enum
        enum: ["main", "test"]
        default: "main"
    steps:
      - run:
          name: Work around incremental compilation issues by preserving timestamps in nanoseconds
          command: |
            cd << parameters.project >>
            find -name target -exec tar -zcf targets-<< parameters.config >>.tar.gz -H posix {} +
      - persist_to_workspace:
          root: ~/project
          paths:
            - << parameters.project >>/targets-<< parameters.config >>.tar.gz

  # This step is instant so we can always restore all compilations
  # even the ones that we don't need.
  restore_all_compilations:
    description: "Restores sbt output (the target) folder from cache."
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - restore_single_project_compilation:
          project: sbt-paytouch
      - restore_single_project_compilation:
          project: domain
      - restore_single_project_compilation:
          project: pt_core
      - restore_single_project_compilation:
          project: pt_ordering

  restore_single_project_compilation:
    description: "Restores sbt output (the target) folder from cache."
    parameters:
      project:
        description: project
        type: string
    steps:
      - run:
          name: Restoring << parameters.project >> compilation (step succeeds even if restoration fails)
          command: |
            tar -xf /tmp/workspace/<< parameters.project >>/targets-main.tar.gz --directory ~/project/<< parameters.project >> || true
            tar -xf /tmp/workspace/<< parameters.project >>/targets-test.tar.gz --directory ~/project/<< parameters.project >> || true
