version: 2.1

jobs:
  build:
    executor: jdk
    steps:
      - checkout
      - run:
          name: Trigger build for modified projects
          shell: /bin/bash
          command: tools/ci/core/build.sh

  sbt-paytouch:
    executor: jdk
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/
      - restore_dependencies
      - run:
          command: |
            cd sbt-paytouch
            sbt compile
      - cache_dependencies
      - persist_to_workspace:
          root: ~/
          paths:
            - project/sbt-paytouch/target*
            - project/domain/target*
            - project/pt_core/target*
            - project/pt_ordering/target*

  domain:
    executor: jdk
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/
      - restore_dependencies
      - run:
          command: |
            cd domain
            sbt test
      - cache_dependencies
      - persist_to_workspace:
          root: ~/
          paths:
            - project/sbt-paytouch/target*
            - project/domain/target*
            - project/pt_core/target*
            - project/pt_ordering/target*

  pt_core:
    executor: jdk
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/
      - restore_dependencies
      - run:
          command: |
            cd pt_core
            sbt test
      - cache_dependencies
      - persist_to_workspace:
          root: ~/
          paths:
            - project/sbt-paytouch/target*
            - project/domain/target*
            - project/pt_core/target*
            - project/pt_ordering/target*

  pt_ordering:
    executor: jdk
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/
      - restore_dependencies
      - run:
          command: |
            cd pt_ordering
            sbt test
      - cache_dependencies
      - persist_to_workspace:
          root: ~/
          paths:
            - project/sbt-paytouch/target*
            - project/domain/target*
            - project/pt_core/target*
            - project/pt_ordering/target*

executors:
  jdk:
    docker:
      - image: circleci/openjdk:8

commands:
  cache_dependencies:
    description: "Caches coursier, ivy2, m2 and sbt artifacts."
    steps:
      - save_cache:
          key: dependencies
          paths:
            - "~/.cache/coursier"
            - "~/.ivy2/cache"
            - "~/.m2"
            - "~/.sbt"

  restore_dependencies:
    description: "Restores coursier, ivy2, m2 and sbt artifacts from cache."
    steps:
      - restore_cache:
          key: dependencies
