package io.paytouch.core.entities

import java.util.UUID

import io.paytouch.core.data.model.enums.{ ArticleScope, ChangeReason, UnitType }

final case class BundleCreation(
    name: String,
    description: ResettableString,
    categoryIds: Seq[UUID],
    brandId: ResettableUUID,
    supplierIds: Seq[UUID],
    sku: ResettableString,
    upc: ResettableString,
    cost: ResettableBigDecimal,
    price: BigDecimal,
    unit: UnitType,
    margin: ResettableBigDecimal,
    trackInventory: Option[Boolean],
    trackInventoryParts: Option[Boolean],
    active: Option[Boolean],
    applyPricingToAllLocations: Option[Boolean],
    discountable: Option[Boolean],
    avatarBgColor: ResettableString,
    isService: Option[Boolean],
    orderRoutingBar: Option[Boolean],
    orderRoutingKitchen: Option[Boolean],
    orderRoutingEnabled: Option[Boolean],
    variants: Seq[VariantOptionTypeUpsertion],
    variantProducts: Seq[VariantProductCreation],
    locationOverrides: Map[UUID, Option[ProductLocationUpdate]],
    imageUploadIds: Seq[UUID],
    bundleSets: Seq[BundleSetCreation],
  )
object BundleCreation extends ToArticleCreation[BundleCreation] {

  def convert(t: BundleCreation)(implicit user: UserContext): ArticleCreation =
    ArticleCreation(
      name = t.name,
      description = t.description,
      categoryIds = t.categoryIds,
      brandId = t.brandId,
      supplierIds = t.supplierIds,
      sku = t.sku,
      upc = t.upc,
      cost = t.cost,
      price = t.price,
      unit = t.unit,
      margin = t.margin,
      trackInventory = t.trackInventory,
      trackInventoryParts = t.trackInventoryParts,
      active = t.active,
      applyPricingToAllLocations = t.applyPricingToAllLocations,
      discountable = t.discountable,
      avatarBgColor = t.avatarBgColor,
      isService = t.isService,
      orderRoutingBar = t.orderRoutingBar,
      orderRoutingKitchen = t.orderRoutingKitchen,
      orderRoutingEnabled = t.orderRoutingEnabled,
      variants = t.variants,
      variantProducts = t.variantProducts.map(VariantProductCreation.convert),
      locationOverrides = t.locationOverrides.transform((_, v) => v.map(ProductLocationUpdate.convert)),
      imageUploadIds = t.imageUploadIds,
      scope = ArticleScope.Product,
      `type` = None,
      isCombo = true,
      makesQuantity = None,
      bundleSets = t.bundleSets,
    )
}

final case class BundleUpdate(
    name: Option[String],
    description: ResettableString,
    categoryIds: Option[Seq[UUID]],
    brandId: ResettableUUID,
    supplierIds: Option[Seq[UUID]],
    sku: ResettableString,
    upc: ResettableString,
    cost: ResettableBigDecimal,
    price: Option[BigDecimal],
    unit: Option[UnitType],
    margin: ResettableBigDecimal,
    trackInventory: Option[Boolean],
    trackInventoryParts: Option[Boolean],
    active: Option[Boolean],
    applyPricingToAllLocations: Option[Boolean],
    discountable: Option[Boolean],
    avatarBgColor: ResettableString,
    isService: Option[Boolean],
    orderRoutingBar: Option[Boolean],
    orderRoutingKitchen: Option[Boolean],
    orderRoutingEnabled: Option[Boolean],
    variants: Option[Seq[VariantOptionTypeUpsertion]],
    variantProducts: Option[Seq[VariantProductUpdate]],
    locationOverrides: Map[UUID, Option[ProductLocationUpdate]],
    imageUploadIds: Option[Seq[UUID]],
    reason: ChangeReason = ChangeReason.Manual,
    notes: Option[String],
    bundleSets: Option[Seq[BundleSetUpdate]],
  )

object BundleUpdate extends ToArticleUpdate[BundleUpdate] {

  def convert(t: BundleUpdate)(implicit user: UserContext): ArticleUpdate =
    ArticleUpdate(
      name = t.name,
      description = t.description,
      categoryIds = t.categoryIds,
      brandId = t.brandId,
      supplierIds = t.supplierIds,
      sku = t.sku,
      upc = t.upc,
      cost = t.cost,
      price = t.price,
      unit = t.unit,
      margin = t.margin,
      trackInventory = t.trackInventory,
      trackInventoryParts = t.trackInventoryParts,
      active = t.active,
      applyPricingToAllLocations = t.applyPricingToAllLocations,
      discountable = t.discountable,
      avatarBgColor = t.avatarBgColor,
      isService = t.isService,
      orderRoutingBar = t.orderRoutingBar,
      orderRoutingKitchen = t.orderRoutingKitchen,
      orderRoutingEnabled = t.orderRoutingEnabled,
      variants = t.variants,
      variantProducts = t.variantProducts.map(_.map(VariantProductUpdate.convert)),
      locationOverrides = t.locationOverrides.transform((_, v) => v.map(ProductLocationUpdate.convert)),
      imageUploadIds = t.imageUploadIds,
      reason = t.reason,
      notes = t.notes,
      scope = Some(ArticleScope.Product),
      `type` = None,
      isCombo = None,
      makesQuantity = None,
      bundleSets = t.bundleSets,
    )
}
